### ISSUE TITLE
Error running on Ruby 2.3.0

### ISSUE THREAD

**Issue by syamilmj** [mina-deploy/mina#368]
Getting this error when I try to run `mina deploy` on Ruby 2.3.0

```
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0xe792e4 mina-0.3.0> (NoMethodError)
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/mina-0.3.0/bin/mina:5:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/mina:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/mina:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ceneon** [comment]
I'm having the same issue, even on mina v0.3.8 :cry:

**Comment by heliohead** [comment]
Same Error :(
/Users/helio/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ffbac81a0a0 mina-0.3.8> (NoMethodError)

**Comment by san983** [comment]
same here on Ruby 2.1.8

**Comment by quangthang10d4** [comment]
I use RVM to downgrade ruby from 2.3.0 and 2.2.4, reinstall the mina gem and it's working just fine.

**Comment by andretf** [comment]
I am able now to run mina on Ruby 2.3.0 after following the steps by @san983. Thanks man!

**Comment by MFQ** [comment]
@san983  saved my day with Mina else I was planning to go for Capistrano.

**Comment by staycreativedesign** [comment]
Does not work in version 2.2.1 changed to 2.3.1 and worked...

**Comment by MoonShining** [comment]
Does not work in ruby 2.3.1

**Comment by staycreativedesign** [comment]
Moon whats the error youre getting?

**Comment by MoonShining** [comment]
log:

/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0xec0d74 mina-0.3.8> (NoMethodError)
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/mina-0.3.8/bin/mina:5:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/mina:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/mina:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

I use RVM to downgrade ruby from 2.3.1 and 2.2.5, reinstall mina and it's working just fine.

**Comment by staycreativedesign** [comment]
In my instance I uninstalled mina... used rvm 2.3.1 and installed mina and it worked
